apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-dashboard-service-dpl
  namespace: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-dashboard-service
  template:
    metadata:
      labels:
        app: admin-dashboard-service
    spec:
      containers:
      - name: admin-dashboard-service
        image: ${FULL_IMAGE_NAME}
        ports:
        - containerPort: 3000
