apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard-service-svc
  namespace: microservice
spec:
  selector:
    app: admin-dashboard-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
